<?php

/**
 * @file
 * This module holds functions useful for theming per role.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_role_extra_field().
 */
function role_appearance_role_extra_field_info() {
  return ['role_theme' => 'role_theme'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function role_appearance_form_user_role_form_alter(&$form, FormStateInterface $form_state) {
  $role = $form_state->getFormObject()->getEntity();
  /** @var Drupal\role\Service\RoleControlManagerInterface $control_manager */
  $control_manager = Drupal::service('role.control_manager');
  $theme_field_name = $control_manager->getExtraFieldKey('role_theme');

  $themes =  \Drupal::service('theme_handler')->listInfo();
  foreach ($themes as $key => $value) {
    $options[$key] = $value->info['name'];
  }

  $form[$theme_field_name] = [
    '#type' => 'select',
    '#title' => t('Installed themes'),
    '#description' => t('Installed themes'),
    '#default_value' => $role->getThirdPartySetting('role', $theme_field_name),
    '#options' => $options,
    '#weight' => 50
  ];
}
